name: Octo Organization CI
on:
  push:
    branches:
      - main
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:
  build:
    runs-on: 
      - self-hosted
      - linux
      - x64
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello from Octo Organization

