name: Octo Organization CI
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-small:
    runs-on: 
      - self-hosted
      - linux
      - x64
      - pimq-runners
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: |
          docker --version
          docker ps
          docker-compose --version
          git --version
          node --version
          yarn --version
          zip --version
          jq --version
          kubectl version --client
          mysql --version
          df -h
      - name: test update eks
        run: aws eks --region ap-northeast-1 update-kubeconfig --name dev-eksV1
        shell: bash
      - name: check kubectl
        run: kubectl version
      - name: deploy to eks
        run: kubectl set image -n dev deployment/schedule schedule=pimq/schedule:dev-latest


     
